#pragma once

#ifdef SDL_WINDOW_API
 // From SDL_scancode.h
    #define ALALBA_A  4
    #define ALALBA_B  5
    #define ALALBA_C  6
    #define ALALBA_D  7
    #define ALALBA_E  8
    #define ALALBA_F  9
    #define ALALBA_G  10
    #define ALALBA_H  11
    #define ALALBA_I  12
    #define ALALBA_J  13
    #define ALALBA_K  14
    #define ALALBA_L  15
    #define ALALBA_M  16
    #define ALALBA_N  17
    #define ALALBA_O  18
    #define ALALBA_P  19
    #define ALALBA_Q  20
    #define ALALBA_R  21
    #define ALALBA_S  22
    #define ALALBA_T  23
    #define ALALBA_U  24
    #define ALALBA_V  25
    #define ALALBA_W  26
    #define ALALBA_X  27
    #define ALALBA_Y  28
    #define ALALBA_Z  29

    #define ALALBA_1  30
    #define ALALBA_2  31
    #define ALALBA_3  32
    #define ALALBA_4  33
    #define ALALBA_5  34
    #define ALALBA_6  35
    #define ALALBA_7  36
    #define ALALBA_8  37
    #define ALALBA_9  38
    #define ALALBA_0  39

    #define ALALBA_RETURN  40
    #define ALALBA_ESCAPE  41
    #define ALALBA_BACKSPACE  42
    #define ALALBA_TAB  43
    #define ALALBA_SPACE  44

    #define ALALBA_MINUS  45
    #define ALALBA_EQUALS  46
    #define ALALBA_LEFTBRACKET  47
    #define ALALBA_RIGHTBRACKET  48
    #define ALALBA_BACKSLASH  49 
    #define ALALBA_NONUSHASH  50 
    #define ALALBA_SEMICOLON  51
    #define ALALBA_APOSTROPHE  52
    #define ALALBA_GRAVE  53 
    #define ALALBA_COMMA  54
    #define ALALBA_PERIOD  55
    #define ALALBA_SLASH  56

    #define ALALBA_CAPSLOCK  57

    #define ALALBA_F1  58
    #define ALALBA_F2  59
    #define ALALBA_F3  60
    #define ALALBA_F4  61
    #define ALALBA_F5  62
    #define ALALBA_F6  63
    #define ALALBA_F7  64
    #define ALALBA_F8  65
    #define ALALBA_F9  66
    #define ALALBA_F10  67
    #define ALALBA_F11  68
    #define ALALBA_F12  69

    #define ALALBA_PRINTSCREEN  70
    #define ALALBA_SCROLLLOCK  71
    #define ALALBA_PAUSE  72
    #define ALALBA_INSERT  73 
    #define ALALBA_HOME  74
    #define ALALBA_PAGEUP  75
    #define ALALBA_DELETE  76
    #define ALALBA_END  77
    #define ALALBA_PAGEDOWN  78
    #define ALALBA_RIGHT  79
    #define ALALBA_LEFT  80
    #define ALALBA_DOWN  81
    #define ALALBA_UP  82

    #define ALALBA_NUMLOCKCLEAR  83 
    #define ALALBA_KP_DIVIDE  84
    #define ALALBA_KP_MULTIPLY  85
    #define ALALBA_KP_MINUS  86
    #define ALALBA_KP_PLUS  87
    #define ALALBA_KP_ENTER  88
    #define ALALBA_KP_1  89
    #define ALALBA_KP_2  90
    #define ALALBA_KP_3  91
    #define ALALBA_KP_4  92
    #define ALALBA_KP_5  93
    #define ALALBA_KP_6  94
    #define ALALBA_KP_7  95
    #define ALALBA_KP_8  96
    #define ALALBA_KP_9  97
    #define ALALBA_KP_0  98
    #define ALALBA_KP_PERIOD  99
    #define ALALBA_NONUSBACKSLASH  100 
    #define ALALBA_APPLICATION  101 
    #define ALALBA_POWER  102 
    #define ALALBA_KP_EQUALS  103
    #define ALALBA_F13  104
    #define ALALBA_F14  105
    #define ALALBA_F15  106
    #define ALALBA_F16  107
    #define ALALBA_F17  108
    #define ALALBA_F18  109
    #define ALALBA_F19  110
    #define ALALBA_F20  111
    #define ALALBA_F21  112
    #define ALALBA_F22  113
    #define ALALBA_F23  114
    #define ALALBA_F24  115
    #define ALALBA_EXECUTE  116
    #define ALALBA_HELP  117
    #define ALALBA_MENU  118
    #define ALALBA_SELECT  119
    #define ALALBA_STOP  120
    #define ALALBA_AGAIN  121  
    #define ALALBA_UNDO  122
    #define ALALBA_CUT  123
    #define ALALBA_COPY  124
    #define ALALBA_PASTE  125
    #define ALALBA_FIND  126
    #define ALALBA_MUTE  127
    #define ALALBA_VOLUMEUP  128
    #define ALALBA_VOLUMEDOWN  129
    #define ALALBA_KP_COMMA  133
    #define ALALBA_KP_EQUALSAS400  134

    #define ALALBA_INTERNATIONAL1  135 
    #define ALALBA_INTERNATIONAL2  136
    #define ALALBA_INTERNATIONAL3  137 
    #define ALALBA_INTERNATIONAL4  138
    #define ALALBA_INTERNATIONAL5  139
    #define ALALBA_INTERNATIONAL6  140
    #define ALALBA_INTERNATIONAL7  141
    #define ALALBA_INTERNATIONAL8  142
    #define ALALBA_INTERNATIONAL9  143
    #define ALALBA_LANG1  144 
    #define ALALBA_LANG2  145 
    #define ALALBA_LANG3  146 
    #define ALALBA_LANG4  147
    #define ALALBA_LANG5  148 
    #define ALALBA_LANG6  149 
    #define ALALBA_LANG7  150 
    #define ALALBA_LANG8  151 
    #define ALALBA_LANG9  152 
    #define ALALBA_ALTERASE  153 
    #define ALALBA_SYSREQ  154
    #define ALALBA_CANCEL  155
    #define ALALBA_CLEAR  156
    #define ALALBA_PRIOR  157
    #define ALALBA_RETURN2  158
    #define ALALBA_SEPARATOR  159
    #define ALALBA_OUT  160
    #define ALALBA_OPER  161
    #define ALALBA_CLEARAGAIN  162
    #define ALALBA_CRSEL  163
    #define ALALBA_EXSEL  164

    #define ALALBA_KP_00  176
    #define ALALBA_KP_000  177
    #define ALALBA_THOUSANDSSEPARATOR  178
    #define ALALBA_DECIMALSEPARATOR  179
    #define ALALBA_CURRENCYUNIT  180
    #define ALALBA_CURRENCYSUBUNIT  181
    #define ALALBA_KP_LEFTPAREN  182
    #define ALALBA_KP_RIGHTPAREN  183
    #define ALALBA_KP_LEFTBRACE  184
    #define ALALBA_KP_RIGHTBRACE  185
    #define ALALBA_KP_TAB  186
    #define ALALBA_KP_BACKSPACE  187
    #define ALALBA_KP_A  188
    #define ALALBA_KP_B  189
    #define ALALBA_KP_C  190
    #define ALALBA_KP_D  191
    #define ALALBA_KP_E  192
    #define ALALBA_KP_F  193
    #define ALALBA_KP_XOR  194
    #define ALALBA_KP_POWER  195
    #define ALALBA_KP_PERCENT  196
    #define ALALBA_KP_LESS  197
    #define ALALBA_KP_GREATER  198
    #define ALALBA_KP_AMPERSAND  199
    #define ALALBA_KP_DBLAMPERSAND  200
    #define ALALBA_KP_VERTICALBAR  201
    #define ALALBA_KP_DBLVERTICALBAR  202
    #define ALALBA_KP_COLON  203
    #define ALALBA_KP_HASH  204
    #define ALALBA_KP_SPACE  205
    #define ALALBA_KP_AT  206
    #define ALALBA_KP_EXCLAM  207
    #define ALALBA_KP_MEMSTORE  208
    #define ALALBA_KP_MEMRECALL  209
    #define ALALBA_KP_MEMCLEAR  210
    #define ALALBA_KP_MEMADD  211
    #define ALALBA_KP_MEMSUBTRACT  212
    #define ALALBA_KP_MEMMULTIPLY  213
    #define ALALBA_KP_MEMDIVIDE  214
    #define ALALBA_KP_PLUSMINUS  215
    #define ALALBA_KP_CLEAR  216
    #define ALALBA_KP_CLEARENTRY  217
    #define ALALBA_KP_BINARY  218
    #define ALALBA_KP_OCTAL  219
    #define ALALBA_KP_DECIMAL  220
    #define ALALBA_KP_HEXADECIMAL  221

    #define ALALBA_LCTRL  224
    #define ALALBA_LSHIFT  225
    #define ALALBA_LALT  226 
    #define ALALBA_LGUI  227 
    #define ALALBA_RCTRL  228
    #define ALALBA_RSHIFT  229
    #define ALALBA_RALT  230 
    #define ALALBA_RGUI  231 

    #define ALALBA_MODE  257    

    #define ALALBA_AUDIONEXT  258
    #define ALALBA_AUDIOPREV  259
    #define ALALBA_AUDIOSTOP  260
    #define ALALBA_AUDIOPLAY  261
    #define ALALBA_AUDIOMUTE  262
    #define ALALBA_MEDIASELECT  263
    #define ALALBA_WWW  264
    #define ALALBA_MAIL  265
    #define ALALBA_CALCULATOR  266
    #define ALALBA_COMPUTER  267
    #define ALALBA_AC_SEARCH  268
    #define ALALBA_AC_HOME  269
    #define ALALBA_AC_BACK  270
    #define ALALBA_AC_FORWARD  271
    #define ALALBA_AC_STOP  272
    #define ALALBA_AC_REFRESH  273
    #define ALALBA_AC_BOOKMARKS  274

    #define ALALBA_BRIGHTNESSDOWN  275
    #define ALALBA_BRIGHTNESSUP  276
    #define ALALBA_DISPLAYSWITCH  277 
    #define ALALBA_KBDILLUMTOGGLE  278
    #define ALALBA_KBDILLUMDOWN  279
    #define ALALBA_KBDILLUMUP  280
    #define ALALBA_EJECT  281
    #define ALALBA_SLEEP  282

    #define ALALBA_APP1  283
    #define ALALBA_APP2  284

    #define ALALBA_AUDIOREWIND  285
    #define ALALBA_AUDIOFASTFORWARD  286

#else

  // From glfw3.h
  #define ALALBA_SPACE              32
  #define ALALBA_APOSTROPHE         39  /* ' */
  #define ALALBA_COMMA              44  /* , */
  #define ALALBA_MINUS              45  /* - */
  #define ALALBA_PERIOD             46  /* . */
  #define ALALBA_SLASH              47  /* / */
  #define ALALBA_0                  48
  #define ALALBA_1                  49
  #define ALALBA_2                  50
  #define ALALBA_3                  51
  #define ALALBA_4                  52
  #define ALALBA_5                  53
  #define ALALBA_6                  54
  #define ALALBA_7                  55
  #define ALALBA_8                  56
  #define ALALBA_9                  57
  #define ALALBA_SEMICOLON          59  /* ; */
  #define ALALBA_EQUAL              61  /* = */
  #define ALALBA_A                  65
  #define ALALBA_B                  66
  #define ALALBA_C                  67
  #define ALALBA_D                  68
  #define ALALBA_E                  69
  #define ALALBA_F                  70
  #define ALALBA_G                  71
  #define ALALBA_H                  72
  #define ALALBA_I                  73
  #define ALALBA_J                  74
  #define ALALBA_K                  75
  #define ALALBA_L                  76
  #define ALALBA_M                  77
  #define ALALBA_N                  78
  #define ALALBA_O                  79
  #define ALALBA_P                  80
  #define ALALBA_Q                  81
  #define ALALBA_R                  82
  #define ALALBA_S                  83
  #define ALALBA_T                  84
  #define ALALBA_U                  85
  #define ALALBA_V                  86
  #define ALALBA_W                  87
  #define ALALBA_X                  88
  #define ALALBA_Y                  89
  #define ALALBA_Z                  90
  #define ALALBA_LEFT_BRACKET       91  /* [ */
  #define ALALBA_BACKSLASH          92  /* \ */
  #define ALALBA_RIGHT_BRACKET      93  /* ] */
  #define ALALBA_GRAVE_ACCENT       96  /* ` */
  #define ALALBA_WORLD_1            161 /* non-US #1 */
  #define ALALBA_WORLD_2            162 /* non-US #2 */

  /* Function keys */
  #define ALALBA_ESCAPE             256
  #define ALALBA_ENTER              257
  #define ALALBA_TAB                258
  #define ALALBA_BACKSPACE          259
  #define ALALBA_INSERT             260
  #define ALALBA_DELETE             261
  #define ALALBA_RIGHT              262
  #define ALALBA_LEFT               263
  #define ALALBA_DOWN               264
  #define ALALBA_UP                 265
  #define ALALBA_PAGE_UP            266
  #define ALALBA_PAGE_DOWN          267
  #define ALALBA_HOME               268
  #define ALALBA_END                269
  #define ALALBA_CAPS_LOCK          280
  #define ALALBA_SCROLL_LOCK        281
  #define ALALBA_NUM_LOCK           282
  #define ALALBA_PRINT_SCREEN       283
  #define ALALBA_PAUSE              284
  #define ALALBA_F1                 290
  #define ALALBA_F2                 291
  #define ALALBA_F3                 292
  #define ALALBA_F4                 293
  #define ALALBA_F5                 294
  #define ALALBA_F6                 295
  #define ALALBA_F7                 296
  #define ALALBA_F8                 297
  #define ALALBA_F9                 298
  #define ALALBA_F10                299
  #define ALALBA_F11                300
  #define ALALBA_F12                301
  #define ALALBA_F13                302
  #define ALALBA_F14                303
  #define ALALBA_F15                304
  #define ALALBA_F16                305
  #define ALALBA_F17                306
  #define ALALBA_F18                307
  #define ALALBA_F19                308
  #define ALALBA_F20                309
  #define ALALBA_F21                310
  #define ALALBA_F22                311
  #define ALALBA_F23                312
  #define ALALBA_F24                313
  #define ALALBA_F25                314
  #define ALALBA_KP_0               320
  #define ALALBA_KP_1               321
  #define ALALBA_KP_2               322
  #define ALALBA_KP_3               323
  #define ALALBA_KP_4               324
  #define ALALBA_KP_5               325
  #define ALALBA_KP_6               326
  #define ALALBA_KP_7               327
  #define ALALBA_KP_8               328
  #define ALALBA_KP_9               329
  #define ALALBA_KP_DECIMAL         330
  #define ALALBA_KP_DIVIDE          331
  #define ALALBA_KP_MULTIPLY        332
  #define ALALBA_KP_SUBTRACT        333
  #define ALALBA_KP_ADD             334
  #define ALALBA_KP_ENTER           335
  #define ALALBA_KP_EQUAL           336
  #define ALALBA_LEFT_SHIFT         340
  #define ALALBA_LEFT_CONTROL       341
  #define ALALBA_LEFT_ALT           342
  #define ALALBA_LEFT_SUPER         343
  #define ALALBA_RIGHT_SHIFT        344
  #define ALALBA_RIGHT_CONTROL      345
  #define ALALBA_RIGHT_ALT          346
  #define ALALBA_RIGHT_SUPER        347
  #define ALALBA_MENU               348
#endif