#pragma once
#ifdef SDL_WINDOW_API
  // From SDL_mouse.h
  #define ALALBA_MOUSE_BUTTON(X)       (1 << ((X)-1))
  #define ALALBA_MOUSE_BUTTON_LEFT     1
  #define ALALBA_MOUSE_BUTTON_MIDDLE    2
  #define ALALBA_MOUSE_BUTTON_RIGHT     3
  #define ALALBA_MOUSE_BUTTON_X1       4
  #define ALALBA_MOUSE_BUTTON_X2       5
  #define ALALBA_MOUSE_BUTTON_LMASK    ALALBA_MOUSE_BUTTON(ALALBA_MOUSE_BUTTON_LEFT )
  #define ALALBA_MOUSE_BUTTON_MMASK    ALALBA_MOUSE_BUTTON(ALALBA_MOUSE_BUTTON_MIDDLE )
  #define ALALBA_MOUSE_BUTTON_RMASK    ALALBA_MOUSE_BUTTON(ALALBA_MOUSE_BUTTON_RIGHT )
  #define ALALBA_MOUSE_BUTTON_X1MASK   ALALBA_MOUSE_BUTTON(ALALBA_MOUSE_BUTTON_X1)
  #define ALALBA_MOUSE_BUTTON_X2MASK   ALALBA_MOUSE_BUTTON(ALALBA_MOUSE_BUTTON_X2)

#else
  // From glfw3.h
  #define ALALBA_MOUSE_BUTTON_1         0
  #define ALALBA_MOUSE_BUTTON_2         1
  #define ALALBA_MOUSE_BUTTON_3         2
  #define ALALBA_MOUSE_BUTTON_4         3
  #define ALALBA_MOUSE_BUTTON_5         4
  #define ALALBA_MOUSE_BUTTON_6         5
  #define ALALBA_MOUSE_BUTTON_7         6
  #define ALALBA_MOUSE_BUTTON_8         7
  #define ALALBA_MOUSE_BUTTON_LAST      ALALBA_MOUSE_BUTTON_8
  #define ALALBA_MOUSE_BUTTON_LEFT      ALALBA_MOUSE_BUTTON_1
  #define ALALBA_MOUSE_BUTTON_RIGHT     ALALBA_MOUSE_BUTTON_2
  #define ALALBA_MOUSE_BUTTON_MIDDLE    ALALBA_MOUSE_BUTTON_3
#endif
